name: Build Frontend

on:
  push:
    paths:
      - 'focusstack-frontend/**'
  pull_request:
    paths:
      - 'focusstack-frontend/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: focusstack-frontend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
